# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 16
  stride: 8
# Network config
masknet:
  in_chan: 64
  out_chan: 64
  bn_chan: 128
  hid_size: 128
  chunk_size: 250
  hop_size: 125
  n_repeats: 6
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 120
  batch_size: 4
  num_workers: 6
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  #sep_clean
  task: sep_noisy
  # train_dir: data/wav8k/min/train-100_spare_01
  train_dir: data/wav8k/min/train-100
  valid_dir: data/wav8k/min/dev
  sample_rate: 8000
  n_src: 2
  segment: 3
